In [2]:
# Read panel data with merged macro + AQI features.
pd.set_option('display.max_columns', None)

from pathlib import Path

import pandas as pd

ROOT = Path('/Users/jinyecai/Desktop/ML_Mortgage')
PROC = ROOT / 'processed_mortgage'
MACRO_MERGED = PROC / 'macro_merged'

default_path = MACRO_MERGED / 'panel_default_with_macro.parquet'
prepay_path = MACRO_MERGED / 'panel_prepay_with_macro.parquet'

default_data = pd.read_parquet(default_path)
prepay_data = pd.read_parquet(prepay_path)

print(f'default_data: {default_data.shape}')
print(f'prepay_data:  {prepay_data.shape}')
print('default monthly range:', default_data['monthly_reporting_period'].min(), '->', default_data['monthly_reporting_period'].max())
print('prepay monthly range: ', prepay_data['monthly_reporting_period'].min(), '->', prepay_data['monthly_reporting_period'].max())

default_data.head()

default_data: (3570337, 58)
prepay_data:  (3570337, 58)
default monthly range: 201601 -> 202509
prepay monthly range:  201601 -> 202509

,loan_sequence_number,monthly_reporting_period,rp_yyyymm,file_year_x,loan_id,loan_age,remaining_months_to_legal_maturity,current_actual_upb,interest_bearing_upb,current_interest_rate,estimated_loan_to_value_eltv,modification_flag,y_default,credit_score,first_payment_date,first_time_homebuyer_flag,maturity_date,metropolitan_statistical_area_msa_or_metropolitan_division,mortgage_insurance_percentage_mi_pct,number_of_units,occupancy_status,original_combined_loan_to_value_cltv,original_debt_to_income_dti_ratio,original_upb,original_loan_to_value_ltv,original_interest_rate,channel,prepayment_penalty_mortgage_ppm_flag,amortization_type_formerly_product_type,property_state,property_type,postal_code,loan_purpose,original_loan_term,number_of_borrowers,seller_name,servicer_name,super_conforming_flag,pre_harp_loan_sequence_number,program_indicator,harp_indicator,property_valuation_method,interest_only_i_o_indicator,mortgage_insurance_cancellation_indicator,file_year_y,first_payment_date_dt,maturity_date_dt,year,unrate,cpi,fedfunds,gs10,cpi_yoy,pmms30,fhfa_hpi,fhfa_hpi_yoy,median_aqi,mortgage_treasury_spread
0,F16Q10000006,201603,201603,2016,F16Q10000006,000,240,125000.00,125000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,5.0,238.080,0.36,1.89,0.008916,3.694,233.26,0.069902,47.5,1.804
1,F16Q10000006,201604,201604,2016,F16Q10000006,001,239,124000.00,124000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,5.1,238.992,0.37,1.81,0.011726,3.605,240.61,0.072237,47.5,1.795
2,F16Q10000006,201605,201605,2016,F16Q10000006,002,238,124000.00,124000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,4.8,239.557,0.37,1.81,0.010785,3.600,240.61,0.072237,47.5,1.790
3,F16Q10000006,201606,201606,2016,F16Q10000006,003,237,124000.00,124000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,4.9,240.222,0.38,1.64,0.010793,3.568,240.61,0.072237,47.5,1.928
4,F16Q10000006,201607,201607,2016,F16Q10000006,004,236,123000.00,123000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,4.8,240.101,0.39,1.50,0.008684,3.440,243.72,0.069323,47.5,1.940

In [3]:
# Prepare light feature engineering for default and prepay modeling.
# rename file_year_x as vintage_year
default_data = default_data.rename(columns={'file_year_x': 'vintage_year'})
#check data type of loan_age, if not int, convert to int
if default_data['loan_age'].dtype != 'int':
    default_data['loan_age'] = default_data['loan_age'].astype(int)
default_data.head()

,loan_sequence_number,monthly_reporting_period,rp_yyyymm,vintage_year,loan_id,loan_age,remaining_months_to_legal_maturity,current_actual_upb,interest_bearing_upb,current_interest_rate,estimated_loan_to_value_eltv,modification_flag,y_default,credit_score,first_payment_date,first_time_homebuyer_flag,maturity_date,metropolitan_statistical_area_msa_or_metropolitan_division,mortgage_insurance_percentage_mi_pct,number_of_units,occupancy_status,original_combined_loan_to_value_cltv,original_debt_to_income_dti_ratio,original_upb,original_loan_to_value_ltv,original_interest_rate,channel,prepayment_penalty_mortgage_ppm_flag,amortization_type_formerly_product_type,property_state,property_type,postal_code,loan_purpose,original_loan_term,number_of_borrowers,seller_name,servicer_name,super_conforming_flag,pre_harp_loan_sequence_number,program_indicator,harp_indicator,property_valuation_method,interest_only_i_o_indicator,mortgage_insurance_cancellation_indicator,file_year_y,first_payment_date_dt,maturity_date_dt,year,unrate,cpi,fedfunds,gs10,cpi_yoy,pmms30,fhfa_hpi,fhfa_hpi_yoy,median_aqi,mortgage_treasury_spread
0,F16Q10000006,201603,201603,2016,F16Q10000006,0,240,125000.00,125000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,5.0,238.080,0.36,1.89,0.008916,3.694,233.26,0.069902,47.5,1.804
1,F16Q10000006,201604,201604,2016,F16Q10000006,1,239,124000.00,124000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,5.1,238.992,0.37,1.81,0.011726,3.605,240.61,0.072237,47.5,1.795
2,F16Q10000006,201605,201605,2016,F16Q10000006,2,238,124000.00,124000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,4.8,239.557,0.37,1.81,0.010785,3.600,240.61,0.072237,47.5,1.790
3,F16Q10000006,201606,201606,2016,F16Q10000006,3,237,124000.00,124000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,4.9,240.222,0.38,1.64,0.010793,3.568,240.61,0.072237,47.5,1.928
4,F16Q10000006,201607,201607,2016,F16Q10000006,4,236,123000.00,123000.00,3.750,,,0,686,201604,N,203603,39820,000,1,P,65,41,125000,65,3.75,R,N,FRM,CA,MH,96000,C,240,2,Other sellers,Other servicers,<NA>,<NA>,9,<NA>,7,N,7,2016,2016-04-01,2036-03-01,2016,4.8,240.101,0.39,1.50,0.008684,3.440,243.72,0.069323,47.5,1.940